name: Configuration Update Base
type: module
description: 'Provides basic revert and update functionality for other modules'
# core: 8.x
dependencies:
  - config

# Information added by Drupal.org packaging script on 2016-02-05
version: '8.x-1.0+4-dev'
core: '8.x'
project: 'config_update'
datestamp: 1454691248
